In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
from numpy import dtype

In [2]:
import sys
sys.path.append("../")

from essay_scorer import EssayScorer

In [3]:
es = EssayScorer.load('../head_model')

In [4]:
task1 = 'Fresh water has always been a limited resource in some parts of the world. Today, however, growing worldwide demand has made this a global problem. What are the causes of the increased demand and what measure could governments and individuals take to respond to this problem?'

In [5]:
essay1 = '''Fresh water resource is a worldwide issue, that is related to varied factors, and it should be involve every country in the world. This essay will illustrate some reasons of the increasing demand and some solutions to solve as soon as possible.

Nowadays, because of industrialization, many European country has resolved this problem because every citizen are able to get drinkable water, but there is a huge difference with the third countries. Although, European people do not miss water, limited water resource is becoming a global emergency that could affect every nation.

Firstly, the rising request is related to the overpopulation; that is the reason why Chinese government has tried to reduce and regulate birth, so they have got the power to limit and control the population growth; this is not a reasonable political action to take.

Secondly, the overpopulation has caused a growing demand of food, so further water has been used by farmer for agriculture; moreover, not all the farms have an appropriate and modern infrastructures and machines to give water to the soil, consequently a huge amount of this natural resource is wasted.

A solution could be taken by local governments, such as, investments in new technologies, which are able to reuse water from soil, or more invested money on the creation of food in laboratories, in this last scenario a vast amount of water could be saved.

In addition, global warming has affected significantly this issue, for this reason international cooperation should try to reduce the environment changing to preserve water, avoiding deforestation and pollution, increasing renewable energy.
I would suggest teaching and educating children and students to save water in everyday life, these lessons could help them to notice their usage in their private house.

In conclusion, I think some solutions could be found to fix the problem; however, we should work all together to make the difference.'''

In [6]:
# band 6
es.score(task1, essay1)

/home/ubuntu/sync_dir/src/exp/../essay_scorer.py:175: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /home/conda/feedstock_root/build_artifacts/libtorch_1730833640211/work/torch/csrc/utils/tensor_new.cpp:278.)
  return self.essay_scorer_head_model(torch.FloatTensor([embedding]))


tensor([[5.8518]], grad_fn=<AddmmBackward0>)

In [7]:
import torch

from transformers import pipeline
from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "meta-llama/Llama-3.2-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side="left")

pipe = pipeline(
    "text-generation", 
    model=model_id, 
    torch_dtype=torch.bfloat16, 
    device_map="auto",
    max_new_tokens=600,
    pad_token_id = tokenizer.eos_token_id
)

# pipe("Just answer for 1 question with single word. What is the capital of US? Answer - ")


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [8]:
PROMT = (
    'Your task is to:\n' +

    'Enhance the essay\'s clarity, grammar, vocabulary, and sentence structure while preserving the original meaning and ideas.\n' +
    'Avoid introducing new arguments or changing the essay’s overall structure or tone.\n' +
    'Limit changes to essential improvements—do not rewrite the essay extensively or modify more than necessary.\n' +
    'Please provide only the revised essay\n' +

    'Topic: {task}\n' +
    'Essay: {essay}\n' +

    '-----------------------\n'
    'Write new essay under this line and nothing else: \n'
    '-----------------------\n'
)

In [9]:
final_prompt1 = PROMT.format(task=task1, essay=essay1)
print(final_prompt1)

Your task is to:
Enhance the essay's clarity, grammar, vocabulary, and sentence structure while preserving the original meaning and ideas.
Avoid introducing new arguments or changing the essay’s overall structure or tone.
Limit changes to essential improvements—do not rewrite the essay extensively or modify more than necessary.
Please provide only the revised essay
Topic: Fresh water has always been a limited resource in some parts of the world. Today, however, growing worldwide demand has made this a global problem. What are the causes of the increased demand and what measure could governments and individuals take to respond to this problem?
Essay: Fresh water resource is a worldwide issue, that is related to varied factors, and it should be involve every country in the world. This essay will illustrate some reasons of the increasing demand and some solutions to solve as soon as possible.

Nowadays, because of industrialization, many European country has resolved this problem because 

In [10]:
piperesult1 = pipe(final_prompt1, pad_token_id=pipe.tokenizer.eos_token_id)[0]['generated_text']
print(piperesult1)

Your task is to:
Enhance the essay's clarity, grammar, vocabulary, and sentence structure while preserving the original meaning and ideas.
Avoid introducing new arguments or changing the essay’s overall structure or tone.
Limit changes to essential improvements—do not rewrite the essay extensively or modify more than necessary.
Please provide only the revised essay
Topic: Fresh water has always been a limited resource in some parts of the world. Today, however, growing worldwide demand has made this a global problem. What are the causes of the increased demand and what measure could governments and individuals take to respond to this problem?
Essay: Fresh water resource is a worldwide issue, that is related to varied factors, and it should be involve every country in the world. This essay will illustrate some reasons of the increasing demand and some solutions to solve as soon as possible.

Nowadays, because of industrialization, many European country has resolved this problem because 

In [11]:
new_essay1 = piperesult1.split('-----------------------')[-1]
print(new_essay1)


Fresh water is a limited resource in many parts of the world, and its increasing demand has become a global issue. The reasons behind this growing demand are multifaceted, and addressing this problem requires a concerted effort from governments and individuals alike. This essay will explore the causes of the increased demand for fresh water and propose measures that can be taken to mitigate this issue.

The rapid growth of the global population has led to an increase in the demand for fresh water. As a result, many countries, particularly those in Asia and Africa, are facing severe water scarcity. The increasing population puts a strain on the available water resources, leading to a shortage of this essential commodity. Furthermore, the growing demand for food and industry also contributes to the increased demand for fresh water. Farmers require large amounts of water for irrigation, and industrial processes also consume significant quantities of water.

Another significant factor con

In [12]:
es.score(task1, new_essay1)

tensor([[7.0322]], grad_fn=<AddmmBackward0>)

In [13]:
task2 = '''
Some people think that the increasing use of computers and mobile phones for communication has a negative effect on young people's reading and writing skills.

To what extent do you agree or disagree?
'''

In [14]:
essay2 = '''
Nowadays, our life improved by technology developments. Although some people think that communication through computers and mobile phones increased and has a detrimental effect on how young generation develop their skills in reading and writing, others think that this impact of technology is not a disadvantage. I strongly belive that young people reading and writing skills have suffered due to increasing usage of computers and mobile phones.

To begin with, technology  increases day by day and we have to be aware of what is new and implement it on our everyday life. It is certainly known that communication through online platforms it is more easier than the usual one and currently it is vital to have at least one tool like mobile phone or computer if someone wants to have an online conversation with somebody else. A survey was conducted on young subjects in 2007, in the United Kingdom and almost 90% of their respondents agreed with the fact that communication using devices is easier and more effective than using traditional ways and they looked more willing to use a device, like a digital book rather than have similar reading like in the previous generations.

To add more, there are many situations which provide that communication using only devices can be deficitary and it involves a lot of disadvantages. First and foremost, young generation can not experience the biggest pleasure of reading a new book, feeling the fragrance of their pages while sitting at the desk. Also, from the primary school, children learn how to effectively write and this situation needs improvement every day, because currently during the classes, many children get distracted and try to avoid what is vital for a society: to know how to correctly write. What is more, it has been proven that writing on a device decrease the rate of concentration in left emisphere of the brain and ought to this issue, many health problems can appear and develop. Nevertheless, technology development is an insurmontable situation that can not be stopped. During the years 2010-2020, a study was made using foreign students from my University and the results shown that those who used devices like mobile phones or computers in order to communicate had a lower rate of learning our mother tongue than others who concentrated on traditional books. Furthermore, a long period of time looking at blue screens affected the visual content and therefore most of them needed to see an Ophtalmologist.

To conclude, it is evident that communication is the most striking feature in our everyday life and both traditional and digital paths can be used, but younger generation needs to be aware of the disadvantages of using most of the time only devices like computers and mobile phones, because the drawbacks can outweigh more than the positive effects.
'''

In [15]:
final_prompt2 = PROMT.format(task=task2, essay=essay2)
print(final_prompt2)

Your task is to:
Enhance the essay's clarity, grammar, vocabulary, and sentence structure while preserving the original meaning and ideas.
Avoid introducing new arguments or changing the essay’s overall structure or tone.
Limit changes to essential improvements—do not rewrite the essay extensively or modify more than necessary.
Please provide only the revised essay
Topic: 
Some people think that the increasing use of computers and mobile phones for communication has a negative effect on young people's reading and writing skills.

To what extent do you agree or disagree?

Essay: 
Nowadays, our life improved by technology developments. Although some people think that communication through computers and mobile phones increased and has a detrimental effect on how young generation develop their skills in reading and writing, others think that this impact of technology is not a disadvantage. I strongly belive that young people reading and writing skills have suffered due to increasing usage 

In [16]:
piperesult2 = pipe(final_prompt2, pad_token_id=pipe.tokenizer.eos_token_id)[0]['generated_text']
print(piperesult2)

Your task is to:
Enhance the essay's clarity, grammar, vocabulary, and sentence structure while preserving the original meaning and ideas.
Avoid introducing new arguments or changing the essay’s overall structure or tone.
Limit changes to essential improvements—do not rewrite the essay extensively or modify more than necessary.
Please provide only the revised essay
Topic: 
Some people think that the increasing use of computers and mobile phones for communication has a negative effect on young people's reading and writing skills.

To what extent do you agree or disagree?

Essay: 
Nowadays, our life improved by technology developments. Although some people think that communication through computers and mobile phones increased and has a detrimental effect on how young generation develop their skills in reading and writing, others think that this impact of technology is not a disadvantage. I strongly belive that young people reading and writing skills have suffered due to increasing usage 

In [17]:
new_essay2 = piperesult2.split('-----------------------')[-1]
print(new_essay2)


In my opinion, the increasing use of computers and mobile phones for communication has a profoundly negative impact on young people's reading and writing skills. While some may argue that technology has improved communication, I firmly believe that the benefits of traditional methods far outweigh the advantages of digital communication.

Firstly, the rise of digital communication has led to a decline in face-to-face interactions, which are essential for developing reading and writing skills. In the past, people would engage in conversations, debates, and discussions, which helped to improve their language skills. However, with the increasing use of computers and mobile phones, people are spending more time interacting with screens than with each other. This has resulted in a decline in the ability to read and write effectively, as well as a decrease in the ability to think critically and express oneself in writing.

Secondly, the use of digital devices for communication has also led t

In [18]:
# band 6
es.score(task2, essay2)

tensor([[5.2816]], grad_fn=<AddmmBackward0>)

In [19]:
es.score(task2, new_essay2)

tensor([[3.0302]], grad_fn=<AddmmBackward0>)

In [20]:
task3 = '''
Many people argue that museums and art galleries should present the nation’s art, as opposed to artworks from other countries. To what extent do you agree or disagree?
'''

In [21]:
essay3 = '''
The cultural value of engaging with museums and art galleries is unquestionable; they exert a great deal of influence on our perception of the world. It is only reasonable to ponder whether or not these outlets of culture should concentrate their efforts on presenting the nation’s own art, and not that of other countries. In my opinion, there should be an attempt to strike a balance and put the objects of national art in the spotlight, while allowing the public to get acquainted with foreign artworks to a certain extent.

If people were to only find sculptures and paintings by national artists in their local museums, that would have a number of positive effects, such as the fame the artists of that country would gain and the pride its citizens would feel for their fellow countrymen. It would promote patriotism and strengthen the image of the country in the eyes of its inhabitants. Local artists would also receive more financial assistance from the government as their works would generate a significant amount of interest, potentially resulting in further development of the local art. However, in order to evolve art needs fresh ideas, and without exposure to a wider range of creativity the world provides, the evolution of local arts may be hindered.

People enjoy art because it appeals to their inner sense of beauty and triggers strong emotions, and whether the masterpiece that causes these feelings belongs to a local or foreign artist is irrelevant. Talent knows no geographical boundaries; therefore, the emphasis should be on how much joy or amazement the work of art brings, rather than on its origin. If that principle were to be followed, we would never have to choose between local and international art. Reducing our museums or galleries’ collections to local art works, in my view, would be harmful and go against the democratic nature of art.

To sum up, it seems to me that a country has nothing to lose by allowing its people to admire art created elsewhere in the world. A conscious choice by the government to support local artists while hosting exhibitions from other countries could prove the most beneficial.
'''

In [22]:
final_prompt3 = PROMT.format(task=task3, essay=essay3)
print(final_prompt3)

Your task is to:
Enhance the essay's clarity, grammar, vocabulary, and sentence structure while preserving the original meaning and ideas.
Avoid introducing new arguments or changing the essay’s overall structure or tone.
Limit changes to essential improvements—do not rewrite the essay extensively or modify more than necessary.
Please provide only the revised essay
Topic: 
Many people argue that museums and art galleries should present the nation’s art, as opposed to artworks from other countries. To what extent do you agree or disagree?

Essay: 
The cultural value of engaging with museums and art galleries is unquestionable; they exert a great deal of influence on our perception of the world. It is only reasonable to ponder whether or not these outlets of culture should concentrate their efforts on presenting the nation’s own art, and not that of other countries. In my opinion, there should be an attempt to strike a balance and put the objects of national art in the spotlight, while a

In [36]:
piperesult3 = pipe(final_prompt3, pad_token_id=pipe.tokenizer.eos_token_id)[0]['generated_text']
print(piperesult3)

Your task is to:
Enhance the essay's clarity, grammar, vocabulary, and sentence structure while preserving the original meaning and ideas.
Avoid introducing new arguments or changing the essay’s overall structure or tone.
Limit changes to essential improvements—do not rewrite the essay extensively or modify more than necessary.
Please provide only the revised essay
Topic: 
Many people argue that museums and art galleries should present the nation’s art, as opposed to artworks from other countries. To what extent do you agree or disagree?

Essay: 
The cultural value of engaging with museums and art galleries is unquestionable; they exert a great deal of influence on our perception of the world. It is only reasonable to ponder whether or not these outlets of culture should concentrate their efforts on presenting the nation’s own art, and not that of other countries. In my opinion, there should be an attempt to strike a balance and put the objects of national art in the spotlight, while a

In [37]:
new_essay3 = piperesult3.split('-----------------------')[-1]
print(new_essay3)


While museums and art galleries have a significant role in promoting and preserving the nation's artistic heritage, the idea that they should exclusively showcase the country's art is a narrow and limiting perspective. By presenting a diverse range of artworks from around the world, these institutions can foster a more inclusive and nuanced understanding of art and its cultural significance. Moreover, allowing foreign artists to be showcased can bring fresh perspectives and ideas, which can ultimately enrich the local art scene.

On the other hand, some argue that featuring only national art can have positive effects, such as promoting patriotism and boosting the local art market. For instance, local artists may receive increased recognition and financial support, which can lead to further development of the art community. However, this approach can also lead to a lack of diversity and a narrow focus on nationalistic sentiments, which may not be representative of the broader cultural 

In [38]:
# band 8 or band 8.5
es.score(task3, essay3)

tensor([[8.6477]], grad_fn=<AddmmBackward0>)

In [39]:
# band 8 or band 8.5
es.score(task3, new_essay3)

tensor([[6.2544]], grad_fn=<AddmmBackward0>)

In [45]:
piperesult_merged = pipe([final_prompt1, final_prompt2, final_prompt3], pad_token_id=pipe.tokenizer.eos_token_id)

In [48]:
print(len(piperesult_merged))
print(piperesult_merged[0])

3
[{'generated_text': "Your task is to:\nEnhance the essay's clarity, grammar, vocabulary, and sentence structure while preserving the original meaning and ideas.\nAvoid introducing new arguments or changing the essay’s overall structure or tone.\nLimit changes to essential improvements—do not rewrite the essay extensively or modify more than necessary.\nPlease provide only the revised essay\nTopic: Fresh water has always been a limited resource in some parts of the world. Today, however, growing worldwide demand has made this a global problem. What are the causes of the increased demand and what measure could governments and individuals take to respond to this problem?\nEssay: Fresh water resource is a worldwide issue, that is related to varied factors, and it should be involve every country in the world. This essay will illustrate some reasons of the increasing demand and some solutions to solve as soon as possible.\n\nNowadays, because of industrialization, many European country has